[versions]
dockcrossPlugin = "0.3.0"
jniAccessGenerator = "1.1.7"
nexusPublishPlugin = "2.0.0"

[libraries]
jniAccessGenerator = { module = "tel.schich:jni-access-generator", version.ref = "jniAccessGenerator" }

[plugins]
dockcross = { id = "tel.schich.dockcross", version.ref = "dockcrossPlugin" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublishPlugin" }